### model
model_name_or_path: /mnt/scratch/users/40645696/Llama-3.1-8B-Instruct/Llama-3.1-8B-Instruct
### quantization_bit: 4
### quantization_method: bitsandbytes  # choices: [bitsandbytes (4/8), hqq (2/3/4/5/6/8), eetq (8)]
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 8

### dataset
dataset: ambigQA_train_SPLADE3
template: llama3
### cutoff_len: 21092
### max_samples: 2250
overwrite_cache: true
preprocessing_num_workers: 8

### output
output_dir: /mnt/scratch/users/40645696/llama-3.1-8b-clariq/lora/ambig_splade/sft_sip_corrected_prompt/confident
logging_steps: 1
save_steps: 100
plot_loss: true
overwrite_output_dir: true


### train
### resume_from_checkpoint: /mnt/scratch/users/40645696/llama-3.1-8b-clariq/lora/mixed/sft_sip_corrected_prompt/confident/checkpoint-1800
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 3.0e-6
num_train_epochs: 1.5
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 3200000

### eval
val_size: 0.15
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 16

