### model
model_name_or_path: /mnt/scratch/users/40645696/qwen2.5-72b-clariq/Qwen/hub/Qwen/Qwen2.5-72B-Instruct
quantization_bit: 4
quantization_method: bitsandbytes  # choices: [bitsandbytes (4/8), hqq (2/3/4/5/6/8), eetq (8)]
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: claric_sip_adv_train
template: qwen
cutoff_len: 8192
max_samples: 50
overwrite_cache: true
preprocessing_num_workers: 64

### output
output_dir: /mnt/scratch/users/40645696/qwen2.5-72b-clariq/lora/adv_claric/sft_sip_corrected_prompt/confident
logging_steps: 1
save_steps: 100
plot_loss: true
overwrite_output_dir: true


### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 3.0e-5
num_train_epochs: 4
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 3200000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 800

